/* LUMI Academic OS — local-first academic engine */
const LUMI_DB={name:'lumi-academic',version:1,stores:['subjects','notes','cards','sessions','plans','settings']};
function openLumiDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(LUMI_DB.name,LUMI_DB.version);r.onupgradeneeded=()=>{for(const s of LUMI_DB.stores)if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:'id',autoIncrement:true});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbPut(store,value){const db=await openLumiDB();return new Promise((res,rej)=>{const req=db.transaction(store,'readwrite').objectStore(store).put(value);req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function dbAll(store){const db=await openLumiDB();return new Promise((res,rej)=>{const req=db.transaction(store).objectStore(store).getAll();req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function dbClear(store){const db=await openLumiDB();return new Promise((res,rej)=>{const req=db.transaction(store,'readwrite').objectStore(store).clear();req.onsuccess=()=>res();req.onerror=()=>rej(req.error)})}
function lumiToast(text){let t=document.querySelector('.lumi-toast');if(!t){t=document.createElement('div');t.className='lumi-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
function lumiModal(title,body,actions=''){const old=document.querySelector('.lumi-modal');if(old)old.remove();const w=document.createElement('div');w.className='lumi-modal';w.innerHTML=`<div class="lumi-modal-card"><button class="modal-close" aria-label="Close">×</button><span class="eyebrow">LUMI CORE</span><h2>${title}</h2><div class="modal-body">${body}</div><div class="modal-actions">${actions}</div></div>`;document.body.appendChild(w);w.querySelector('.modal-close').onclick=()=>w.remove();w.addEventListener('click',e=>{if(e.target===w)w.remove()});return w}
async function addSubject(){const m=lumiModal('Nueva materia','<label class="lumi-field">Nombre<input id="subjectName" maxlength="80" placeholder="Ej. Historia"></label><label class="lumi-field">Docente<input id="subjectTeacher" maxlength="80" placeholder="Opcional"></label><label class="lumi-field">Objetivo<select id="subjectGoal"><option>Preparar examen</option><option>Mantenerme al día</option><option>Mejorar mi promedio</option></select></label>','<button class="ghost modal-cancel">Cancelar</button><button class="primary" id="saveSubject">Crear materia</button>');m.querySelector('.modal-cancel').onclick=()=>m.remove();m.querySelector('#saveSubject').onclick=async()=>{const name=m.querySelector('#subjectName').value.trim();if(!name)return lumiToast('Escribí un nombre para la materia.');await dbPut('subjects',{name,teacher:m.querySelector('#subjectTeacher').value.trim(),goal:m.querySelector('#subjectGoal').value,progress:0,created:new Date().toISOString()});m.remove();lumiToast('Materia creada.');if(window.renderAcademic)window.renderAcademic()}}
async function exportLumiBackup(){const data={version:1,exportedAt:new Date().toISOString()};for(const s of LUMI_DB.stores)data[s]=await dbAll(s);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lumi-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);lumiToast('Backup exportado.')}
async function importLumiBackup(file){try{const data=JSON.parse(await file.text());for(const s of LUMI_DB.stores){await dbClear(s);for(const item of (data[s]||[]))await dbPut(s,item)}lumiToast('Backup restaurado.');if(window.renderAcademic)window.renderAcademic()}catch(e){lumiToast('El backup no es válido.')}}
async function startExamMode(){const m=lumiModal('Modo examen','<p class="muted">Elegí una duración y estudiá sin distracciones.</p><label class="lumi-field">Duración<select id="examMinutes"><option value="20">20 minutos</option><option value="30" selected>30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option></select></label><div id="examClock" class="exam-clock">30:00</div>','<button class="ghost modal-cancel">Cancelar</button><button class="primary" id="beginExam">Comenzar examen</button>');m.querySelector('#examMinutes').onchange=e=>m.querySelector('#examClock').textContent=e.target.value+':00';m.querySelector('.modal-cancel').onclick=()=>m.remove();m.querySelector('#beginExam').onclick=()=>{let sec=Number(m.querySelector('#examMinutes').value)*60;m.querySelector('.modal-body').innerHTML='<div class="exam-clock" id="liveExamClock"></div><textarea class="exam-answer" placeholder="Escribí tus respuestas aquí..."></textarea><p class="muted">Modo examen activo.</p>';m.querySelector('.modal-actions').innerHTML='<button class="primary" id="finishExam">Finalizar</button>';const tick=()=>{const x=m.querySelector('#liveExamClock');if(!x)return;x.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(timer);lumiToast('Tiempo terminado.');return}sec--};tick();const timer=setInterval(tick,1000);m.querySelector('#finishExam').onclick=async()=>{clearInterval(timer);await dbPut('sessions',{type:'exam',minutes:Number(m.querySelector('#examMinutes')?.value)||30,date:new Date().toISOString()});m.remove();lumiToast('Examen finalizado.')}}}
async function saveNote(note){return dbPut('notes',{...note,updatedAt:new Date().toISOString()})}
async function createCard(front,back){return dbPut('cards',{front,back,interval:1,ease:2.5,due:new Date().toISOString(),reviews:0})}
async function reviewCard(cardId,quality){const cards=await dbAll('cards'),c=cards.find(x=>x.id===cardId);if(!c)return;const q=Math.max(0,Math.min(5,quality));c.ease=Math.max(1.3,c.ease+(q>=3?.1:-.2));c.interval=q<3?1:Math.max(1,Math.round(c.interval*c.ease));c.due=new Date(Date.now()+c.interval*86400000).toISOString();c.reviews=(c.reviews||0)+1;await dbPut('cards',c)}