const themeBtn=document.getElementById('theme');const savedTheme=localStorage.getItem('lumi-theme');if(savedTheme==='light')document.body.classList.add('light');if(themeBtn){themeBtn.textContent=document.body.classList.contains('light')?'☀':'☾';themeBtn.onclick=()=>{document.body.classList.toggle('light');const light=document.body.classList.contains('light');localStorage.setItem('lumi-theme',light?'light':'dark');themeBtn.textContent=light?'☀':'☾'}}
function escapeHTML(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function ensureModal(){if(document.getElementById('lumiModal'))return;const el=document.createElement('div');el.id='lumiModal';el.innerHTML='<div class="modal-backdrop"><div class="lumi-modal" role="dialog"><button class="modal-x" id="modalClose">×</button><span class="eyebrow">LUMI</span><h3 id="modalTitle"></h3><p id="modalText" class="muted"></p><div id="modalBody"></div><div class="modal-actions"><button class="ghost" id="modalCancel">Cancelar</button><button class="primary" id="modalConfirm">Guardar</button></div></div></div>';document.body.appendChild(el);modalClose.onclick=closeModal;modalCancel.onclick=closeModal}
function openModal(title,text,body,confirm,callback){ensureModal();modalTitle.textContent=title;modalText.textContent=text||'';modalBody.innerHTML=body||'';modalConfirm.textContent=confirm||'Guardar';modalConfirm.onclick=()=>{callback?.();closeModal()};lumiModal.classList.add('open');setTimeout(()=>document.querySelector('#lumiModal input,#lumiModal textarea')?.focus(),20)}
function closeModal(){document.getElementById('lumiModal')?.classList.remove('open')}
function lumiToast(text){let t=document.querySelector('.lumi-toast');if(!t){t=document.createElement('div');t.className='lumi-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),2200)}
async function addTask(){openModal('Nueva tarea','Guardada en SQLite dentro de tu navegador.','<input class="lumi-input" id="taskTitle" placeholder="Ej. Estudiar matemática"><select class="lumi-input" id="taskPriority"><option>Alta</option><option selected>Media</option><option>Baja</option></select>','Agregar',async()=>{const title=taskTitle.value.trim();if(!title)return lumiToast('Escribí una tarea.');addDbTask(title,taskPriority.value);await renderLumi();lumiToast('Tarea guardada.')})}
async function addNote(){openModal('Nueva nota','Apuntes guardados en SQLite.','<input class="lumi-input" id="noteTitle" placeholder="Título"><textarea class="lumi-input" id="noteBody" rows="7" placeholder="Escribí tus apuntes..."></textarea>','Guardar',async()=>{const title=noteTitle.value.trim();if(!title)return lumiToast('Escribí un título.');addDbNote(title,noteBody.value);await renderLumi();lumiToast('Nota guardada.')})}
async function addSubject(){openModal('Nueva materia','Organizá tu cursada.','<input class="lumi-input" id="subjectName" placeholder="Materia"><input class="lumi-input" id="subjectTeacher" placeholder="Docente (opcional)">','Crear',async()=>{const name=subjectName.value.trim();if(!name)return lumiToast('Escribí una materia.');addDbSubject(name,subjectTeacher.value);await renderLumi();lumiToast('Materia creada.')})}
async function addCard(){openModal('Nueva flashcard','Active Recall guardado localmente.','<input class="lumi-input" id="cardFront" placeholder="Pregunta"><textarea class="lumi-input" id="cardBack" rows="5" placeholder="Respuesta"></textarea>','Crear',async()=>{const f=cardFront.value.trim(),b=cardBack.value.trim();if(!f||!b)return lumiToast('Completá ambos campos.');addDbCard(f,b);await renderLumi();lumiToast('Flashcard creada.')})}
async function addEvent(){openModal('Nuevo evento','Agregá una fecha de estudio o examen.','<input class="lumi-input" id="eventTitle" placeholder="Ej. Examen de Historia"><input class="lumi-input" id="eventDate" type="date"><input class="lumi-input" id="eventTime" type="time">','Agregar',async()=>{const title=eventTitle.value.trim(),date=eventDate.value;if(!title||!date)return lumiToast('Completá título y fecha.');addDbEvent(title,date,eventTime.value);await renderLumi();lumiToast('Evento agregado.')})}
async function toggleTask(id,done){toggleDbTask(id,done);await renderLumi()}
async function removeTask(id){deleteDbTask(id);await renderLumi();lumiToast('Tarea eliminada.')}
function renderTasks(){const box=document.getElementById('tasks');if(!box)return;const rows=dbTasks();box.innerHTML=rows.length?rows.map(t=>`<label class="task"><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask(${t.id},this.checked)"><span><b>${escapeHTML(t.title)}</b><small>${escapeHTML(t.priority)} · SQLite</small></span><em>${escapeHTML(t.priority)}</em><button class="task-delete" aria-label="Eliminar" onclick="event.preventDefault();removeTask(${t.id})">×</button></label>`).join(''):'<p class="muted">No hay tareas todavía.</p>';const c=document.getElementById('doneCount');if(c)c.textContent=rows.filter(t=>t.done).length}
function renderPanels(){const subjects=dbSubjects(),notes=dbNotes(),cards=dbCards(),events=dbEvents(),sessions=dbSessions();const s=document.getElementById('subjects');if(s)s.innerHTML=subjects.length?subjects.map(x=>`<div class="task"><span><b>${escapeHTML(x.name)}</b><small>${escapeHTML(x.teacher||'Sin docente')}</small></span><em>${x.progress}%</em></div>`).join(''):'<p class="muted">Agregá tu primera materia.</p>';const n=document.getElementById('notes');if(n)n.innerHTML=notes.length?notes.slice(0,5).map(x=>`<article class="mini-item"><b>${escapeHTML(x.title)}</b><p>${escapeHTML(x.body).slice(0,140)}</p></article>`).join(''):'<p class="muted">Todavía no hay notas.</p>';const e=document.getElementById('events');if(e)e.innerHTML=events.length?events.slice(0,5).map(x=>`<div class="mini-item"><b>${escapeHTML(x.title)}</b><small>${escapeHTML(x.date)} ${escapeHTML(x.time)}</small></div>`).join(''):'<p class="muted">No hay eventos.</p>';for(const [id,value] of [['subjectStat',subjects.length],['noteStat',notes.length],['cardStat',cards.length],['sessionStat',sessions.length]]){const el=document.getElementById(id);if(el)el.textContent=value}}
async function renderLumi(){renderTasks();renderPanels()}
function lumiBrain(){openModal('LUMI Assistant','Motor local: no necesita API ni cuenta.','<textarea class="lumi-input" id="brainInput" rows="5" placeholder="Ej. Tengo examen el viernes y dos tareas pendientes..."></textarea><div id="brainAnswer" class="brain-result muted">LUMI detecta tareas, exámenes, repasos, notas y Focus.</div>','Analizar',()=>{const r=LUMI_CORE.respond(brainInput.value);brainAnswer.textContent=r.text})}
let seconds=1500,timer=null;function renderTimer(){const e=document.getElementById('timer');if(e)e.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}function startTimer(){const b=document.getElementById('timerBtn');if(timer){clearInterval(timer);timer=null;b.textContent='Continuar';return}if(seconds<=0)seconds=1500;b.textContent='Pausar';timer=setInterval(()=>{seconds--;renderTimer();if(seconds<=0){clearInterval(timer);timer=null;addDbSession(25);b.textContent='Completado';lumiToast('Sesión Focus guardada en SQLite.');renderPanels()}},1000)}
window.addEventListener('load',async()=>{try{await initSQLite();await renderLumi();renderTimer()}catch(e){console.error(e);lumiToast('No se pudo iniciar SQLite. Recargá la página.')}});