const themeBtn=document.getElementById('theme');const saved=localStorage.getItem('lumi-theme');if(saved==='light')document.body.classList.add('light');if(themeBtn){themeBtn.textContent=document.body.classList.contains('light')?'☀':'☾';themeBtn.onclick=()=>{document.body.classList.toggle('light');const light=document.body.classList.contains('light');localStorage.setItem('lumi-theme',light?'light':'dark');themeBtn.textContent=light?'☀':'☾'}}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
function ensureModal(){if(document.getElementById('lumiModal'))return;const s=document.createElement('div');s.id='lumiModal';s.innerHTML='<div class="modal-backdrop"><div class="lumi-modal" role="dialog" aria-modal="true"><button class="modal-x" onclick="closeModal()">×</button><span class="eyebrow">LUMI CORE</span><h3 id="modalTitle">Nueva acción</h3><p id="modalText" class="muted"></p><div id="modalBody"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancelar</button><button class="primary" id="modalConfirm">Confirmar</button></div></div></div>';document.body.appendChild(s)}
function openModal(title,text,body='',confirm='Confirmar,cb'){ensureModal();document.getElementById('modalTitle').textContent=title;document.getElementById('modalText').textContent=text;document.getElementById('modalBody').innerHTML=body;const b=document.getElementById('modalConfirm');b.textContent=confirm;b.onclick=()=>{if(typeof window._modalCallback==='function')window._modalCallback();else closeModal()};document.getElementById('lumiModal').classList.add('open')}
function closeModal(){document.getElementById('lumiModal')?.classList.remove('open');window._modalCallback=null}
function addTask(){openModal('Nueva tarea','Organizá una tarea para tu espacio académico.','<input class="lumi-input" id="newTaskTitle" placeholder="Ej. Estudiar matemática" autofocus><select class="lumi-input" id="newTaskPriority"><option>Alta</option><option selected>Media</option><option>Baja</option></select>','Agregar');window._modalCallback=()=>{const title=document.getElementById('newTaskTitle').value.trim();if(!title)return;const task=document.createElement('label');task.className='task';task.innerHTML=`<input type="checkbox"><span><b>${escapeHTML(title)}</b><small>Agregada ahora · LUMI</small></span><em>${escapeHTML(document.getElementById('newTaskPriority').value)}</em>`;document.getElementById('tasks')?.appendChild(task);task.querySelector('input').addEventListener('change',updateDone);saveTasks();closeModal()}}
function updateDone(){const checked=document.querySelectorAll('.task input:checked').length;const counter=document.getElementById('doneCount');if(counter)counter.textContent=3+checked;saveTasks()}
function saveTasks(){const tasks=[...document.querySelectorAll('#tasks .task')].map(t=>({title:t.querySelector('b')?.textContent||'',done:t.querySelector('input')?.checked||false,meta:t.querySelector('small')?.textContent||'',priority:t.querySelector('em')?.textContent||''}));localStorage.setItem('lumi-tasks',JSON.stringify(tasks))}
function loadTasks(){const raw=localStorage.getItem('lumi-tasks');if(!raw)return;try{const tasks=JSON.parse(raw),box=document.getElementById('tasks');if(!box||!tasks.length)return;box.innerHTML='';tasks.forEach(t=>{const el=document.createElement('label');el.className='task';el.innerHTML=`<input type="checkbox" ${t.done?'checked':''}><span><b>${escapeHTML(t.title)}</b><small>${escapeHTML(t.meta)}</small></span><em>${escapeHTML(t.priority)}</em>`;box.appendChild(el);el.querySelector('input').addEventListener('change',updateDone)});updateDone()}catch(e){localStorage.removeItem('lumi-tasks')}}
function demoAI(){openModal('LUMI Study Assistant','Elegí qué querés estudiar y LUMI prepara una sesión con herramientas de aprendizaje.','<input class="lumi-input" id="studyTopic" placeholder="Ej. Revolución Francesa"><div class="quick-grid"><button class="ghost" onclick="setTopic(\'Resumen\')">Resumen</button><button class="ghost" onclick="setTopic(\'Preguntas\')">Preguntas</button><button class="ghost" onclick="setTopic(\'Flashcards\')">Flashcards</button></div>','Preparar');window._modalCallback=()=>{const q=document.getElementById('studyTopic').value.trim();if(!q)return;closeModal();location.href='study.html?topic='+encodeURIComponent(q)}}
function setTopic(kind){const i=document.getElementById('studyTopic');if(i)i.dataset.mode=kind}
let seconds=1500,interval=null;function renderTimer(){const el=document.getElementById('timer');if(!el)return;const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');el.textContent=`${m}:${s}`}
function startTimer(){const btn=document.getElementById('timerBtn');if(!btn)return;if(interval){clearInterval(interval);interval=null;btn.textContent='Continuar';btn.classList.remove('running');return}if(seconds===0){seconds=1500;renderTimer()}btn.textContent='Pausar';btn.classList.add('running');interval=setInterval(()=>{if(seconds>0){seconds--;renderTimer()}else{clearInterval(interval);interval=null;btn.textContent='Completado';btn.classList.remove('running');openModal('Focus completado','Terminaste tu sesión de concentración.','<p class="muted">Tomate unos minutos para descansar antes de empezar otro bloque.</p>','Listo');window._modalCallback=closeModal}},1000)}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadTasks();document.querySelectorAll('.task input').forEach(x=>x.addEventListener('change',updateDone));renderTimer();