/* LUMI Games — four playable study modes */
(function(){
'use strict';
const $=id=>document.getElementById(id), area=()=>$('gameArea');
const read=(key, fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fallback=[
{q:'¿Qué método ayuda a recordar mejor?',a:'Repasar activamente',wrong:['Leer una vez y olvidar','No revisar los errores','Estudiar sin pausas']},
{q:'¿Qué conviene hacer cuando cometés un error?',a:'Entender por qué ocurrió',wrong:['Ignorarlo','Borrar todo','Dejar de estudiar']},
{q:'¿Qué puede hacer LUMI con tus notas?',a:'Convertirlas en actividades',wrong:['Publicarlas','Eliminarlas','Compartirlas automáticamente']}
];
let focusTimer=null;
function shell(title,sub,body){area().innerHTML=`<div class="game-screen"><div class="game-screen-head"><div><span class="section-kicker">LUMI PLAY</span><h3>${esc(title)}</h3><p>${esc(sub)}</p></div><button class="game-back" id="gameBack">Volver</button></div>${body}</div>`;$('gameBack').onclick=menu}
function menu(){if(focusTimer){clearInterval(focusTimer);focusTimer=null}area().innerHTML=`<div class="game-welcome"><span class="section-kicker">PLAY & LEARN</span><h3>Elegí un juego</h3><p>Actividades cortas para estudiar sin que se sienta como tarea.</p><div class="game-menu-grid"><button class="game-choice" id="gQuiz"><span class="game-choice-icon">?</span><b>Quiz rápido</b><small>Preguntas con opciones y puntaje.</small><strong>Jugar →</strong></button><button class="game-choice" id="gMemory"><span class="game-choice-icon">◇</span><b>Memoria</b><small>Encontrá pares y recordá conceptos.</small><strong>Jugar →</strong></button><button class="game-choice" id="gNotes"><span class="game-choice-icon">≡</span><b>Quiz de apuntes</b><small>Convertí tus notas guardadas en preguntas.</small><strong>Jugar →</strong></button><button class="game-choice" id="gFocus"><span class="game-choice-icon">◷</span><b>Misión Focus</b><small>Una sesión ajustable con progreso visual.</small><strong>Empezar →</strong></button></div></div>`;$('gQuiz').onclick=quiz;$('gMemory').onclick=memory;$('gNotes').onclick=noteQuiz;$('gFocus').onclick=focus}
function normalizeNotes(){return read('lumi-notes',[]).filter(n=>n&&(n.title||n.content)).map(n=>({title:n.title||'Apunte',content:String(n.content||'').trim()})).filter(n=>n.content)}
function buildQuestions(source){return source||fallback}
function quiz(source){const data=buildQuestions(source);let index=0,score=0,locked=false;function draw(){locked=false;const x=data[index];const options=[x.a,...(x.wrong||[])].slice(0,4).sort(()=>Math.random()-.5);shell('Quiz rápido',`Pregunta ${index+1} de ${data.length} · ${score} puntos`,`<div class="quiz-top"><span>PROGRESO</span><b>${index+1}/${data.length}</b><span class="quiz-score">${score} pts</span></div><div class="quiz-progress"><i style="width:${index/data.length*100}%"></i></div><div class="game-question"><span class="question-number">${String(index+1).padStart(2,'0')}</span><h4>${esc(x.q)}</h4><div class="game-options">${options.map(o=>`<button class="game-option" data-answer="${encodeURIComponent(o)}">${esc(o)}</button>`).join('')}</div></div>`);area().querySelectorAll('.game-option').forEach(b=>b.onclick=()=>{if(locked)return;locked=true;const value=decodeURIComponent(b.dataset.answer),ok=value===x.a;b.classList.add(ok?'correct':'wrong');if(ok)score++;area().querySelectorAll('.game-option').forEach(btn=>{if(decodeURIComponent(btn.dataset.answer)===x.a)btn.classList.add('correct')});setTimeout(()=>{index++;index<data.length?draw():quizResult(data,score)},650)})}draw()}
function quizResult(data,score){shell('Quiz terminado',`${score} de ${data.length} respuestas correctas`,`<div class="game-result"><div class="result-score">${score}<small>/${data.length}</small></div><p>${score===data.length?'Perfecto. Dominaste esta ronda.':score>=data.length/2?'Bien. Una vuelta más y podés subir el puntaje.':'Repasá el contenido y volvé a intentarlo.'}</p><div class="result-actions"><button class="primary small" id="again">Jugar de nuevo</button><button class="soft small" id="backGames">Ver juegos</button></div></div>`);$('again').onclick=()=>quiz(data);$('backGames').onclick=menu}
function memory(){let source=read('lumi-flashcards',[]).filter(Boolean);let pairs=source.slice(0,8).map((x,i)=>({a:x.front||x.question||`Concepto ${i+1}`,b:x.back||x.answer||'Respuesta'}));if(pairs.length<3)pairs=fallback.map(x=>({a:x.q,b:x.a}));pairs=pairs.slice(0,8);let deck=[];pairs.forEach((p,i)=>{deck.push({id:i,text:p.a,kind:'a'});deck.push({id:i,text:p.b,kind:'b'})});deck.sort(()=>Math.random()-.5);let first=null,second=null,matched=0,turns=0,waiting=false;function draw(){shell('Memoria','Encontrá cada concepto junto con su respuesta.',`<div class="memory-head"><span>${matched}/${pairs.length} pares</span><span>Movimientos: ${turns}</span></div><div class="memory-grid">${deck.map((c,i)=>`<button class="memory-tile ${c.matched?'matched':''} ${(i===first||i===second)?'revealed':''}" data-i="${i}"><span>${c.matched||i===first||i===second?esc(c.text):'LUMI'}</span></button>`).join('')}</div>`);area().querySelectorAll('.memory-tile').forEach(b=>b.onclick=()=>{if(waiting)return;const i=+b.dataset.i,c=deck[i];if(c.matched||i===first)return;if(first===null){first=i;draw();return}second=i;turns++;draw();waiting=true;setTimeout(()=>{if(deck[first].id===deck[second].id&&deck[first].kind!==deck[second].kind){deck[first].matched=deck[second].matched=true;matched++}first=second=null;waiting=false;matched===pairs.length?memoryResult(turns):draw()},650)})}draw()}
function memoryResult(turns){shell('Memoria completada','Encontraste todos los pares.',`<div class="game-result"><div class="result-score">${turns}<small> movimientos</small></div><p>Cuantos menos movimientos, mejor.</p><button class="primary small" id="again">Jugar otra vez</button></div>`);$('again').onclick=memory}
function noteQuiz(){const ns=normalizeNotes();if(!ns.length){shell('Quiz de apuntes','No encontramos notas guardadas.',`<div class="empty-game"><strong>Tu banco de apuntes está vacío.</strong><p>Creá una nota en la sección Notas y después volvé a jugar.</p><button class="soft small" id="toNotes">Ir a Notas</button></div>`);$('toNotes').onclick=()=>location.hash='#notas';return}const data=[];ns.slice(0,8).forEach((n,i)=>{const answer=(n.content.split(/[.!?]+/).map(s=>s.trim()).find(Boolean)||n.content).slice(0,180);const others=ns.filter((_,j)=>j!==i).map(x=>(x.content.split(/[.!?]+/).map(s=>s.trim()).find(Boolean)||x.title).slice(0,120));data.push({q:`Según «${n.title}», ¿qué idea aparece en el apunte?`,a:answer,wrong:[...others.slice(0,2),'Ninguna de las anteriores']})});quiz(data)}
function focus(){if(focusTimer)clearInterval(focusTimer);shell('Misión Focus','Elegí una duración y empezá una sesión.',`<div class="focus-game"><div class="focus-clock" id="gameTimer">25:00</div><div class="focus-label"><span>Duración</span><output id="gameValue">25 min</output></div><input id="gameRange" type="range" min="5" max="120" value="25" step="5"><div class="focus-ring" id="focusRing"><div><b id="focusPercent">0%</b><small>completado</small></div></div><div class="focus-actions"><button class="primary small" id="gameStart">Empezar</button><button class="soft small" id="gameReset">Reiniciar</button></div></div>`);let total=1500,left=1500,running=false;const timer=$('gameTimer'),range=$('gameRange'),value=$('gameValue'),ring=$('focusRing'),percent=$('focusPercent');function render(){timer.textContent=fmt(left);value.textContent=Math.round(total/60)+' min';const pct=Math.min(100,(total-left)/total*100);percent.textContent=Math.round(pct)+'%';ring.style.setProperty('--progress',pct*3.6+'deg')}range.oninput=()=>{if(running)return;total=+range.value*60;left=total;render()};$('gameStart').onclick=()=>{if(left<=0)return;if(running){running=false;$('gameStart').textContent='Continuar';return}running=true;$('gameStart').textContent='Pausar';focusTimer=setInterval(()=>{if(!running)return;left--;render();if(left<=0){running=false;clearInterval(focusTimer);focusTimer=null;$('gameStart').textContent='Completado'}},1000)};$('gameReset').onclick=()=>{running=false;if(focusTimer)clearInterval(focusTimer);focusTimer=null;total=+range.value*60;left=total;$('gameStart').textContent='Empezar';render()};render();function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}}
function wire(){if($('startQuiz'))$('startQuiz').onclick=quiz;if($('startMemory'))$('startMemory').onclick=memory;if($('flashGame'))$('flashGame').onclick=memory;if($('noteQuiz'))$('noteQuiz').onclick=noteQuiz;if($('focusGame'))$('focusGame').onclick=focus;menu()}
document.addEventListener('DOMContentLoaded',()=>setTimeout(wire,250));
})();
