/* LUMI Library: local audio + organized PDF shelf + speech reader */
(function(){
  const KEY='lumi-library-v1';
  const state=JSON.parse(localStorage.getItem(KEY)||'{"audio":[],"pdfs":[]}');
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
  let currentAudio=null, currentPdf=null, speechToken=0;
  const inject=()=>{
    const main=document.querySelector('main'); if(!main||document.getElementById('lumi-library')) return;
    const el=document.createElement('section'); el.id='lumi-library'; el.className='section'; el.innerHTML=`
      <div class="section-head"><div><span class="section-kicker">BIBLIOTECA</span><h2>Tu biblioteca</h2><p>Audio para estudiar y PDFs ordenados por materia, todo local.</p></div></div>
      <div class="library-tabs"><button class="library-tab active" data-tab="audio">Audio</button><button class="library-tab" data-tab="pdf">PDFs</button></div>
      <div id="libraryAudio" class="library-panel"></div><div id="libraryPdf" class="library-panel hidden"></div>`;
    main.appendChild(el);
    el.querySelectorAll('.library-tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
    renderAudio(); renderPdf();
  };
  function switchTab(tab){document.querySelectorAll('.library-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.getElementById('libraryAudio').classList.toggle('hidden',tab!=='audio');document.getElementById('libraryPdf').classList.toggle('hidden',tab!=='pdf')}
  function renderAudio(){
    const box=document.getElementById('libraryAudio');if(!box)return;
    box.innerHTML=`<div class="library-toolbar"><div><b>Biblioteca de audio</b><small>MP3 y otros audios del dispositivo</small></div><label class="primary small library-upload">+ Subir audio<input id="audioLibraryInput" type="file" accept="audio/*" multiple hidden></label></div><div class="audio-library-grid">${state.audio.length?state.audio.map((a,i)=>`<article class="audio-card ${currentAudio===i?'playing':''}"><div class="audio-disc"><i></i></div><div class="audio-meta"><strong>${esc(a.name)}</strong><small>${a.type==='book'?'Audiolibro':'Audio de estudio'}</small></div><button class="audio-play" data-i="${i}" aria-label="Reproducir">${currentAudio===i?'Ⅱ':'▶'}</button><button class="audio-more" data-del="${a.id}">×</button></article>`).join(''):'<div class="library-empty">Subí tus primeros audios para armar tu biblioteca.</div>'}</div><div class="retro-player" id="retroPlayer"><div class="retro-screen"><span>LOCAL AUDIO</span><strong id="retroTitle">${currentAudio!=null?esc(state.audio[currentAudio]?.name):'Sin pista seleccionada'}</strong><small id="retroTime">00:00 / 00:00</small></div><div class="retro-controls"><button id="retroPrev">|◀</button><button id="retroMain">${currentAudio!=null?'▶':'■'}</button><button id="retroNext">▶|</button><label class="retro-vol">VOL <input id="retroVolume" type="range" min="0" max="1" step=".01" value=".8"></label><label class="retro-loop"><input id="retroLoop" type="checkbox"> LOOP</label></div><div class="retro-progress"><i id="retroProgress"></i></div><audio id="lumiAudio" preload="metadata"></audio></div>`;
    box.querySelectorAll('.audio-play').forEach(b=>b.onclick=()=>playAudio(+b.dataset.i));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeAudio(b.dataset.del));
    document.getElementById('audioLibraryInput').onchange=e=>[...e.target.files].forEach(addAudio);
    document.getElementById('retroMain').onclick=toggleAudio;document.getElementById('retroPrev').onclick=()=>playAudio(Math.max(0,(currentAudio??0)-1));document.getElementById('retroNext').onclick=()=>playAudio(Math.min(state.audio.length-1,(currentAudio??0)+1));document.getElementById('retroVolume').oninput=e=>{document.getElementById('lumiAudio').volume=+e.target.value};document.getElementById('retroLoop').onchange=e=>{document.getElementById('lumiAudio').loop=e.target.checked};
    const au=document.getElementById('lumiAudio');au.ontimeupdate=updatePlayer;au.onended=()=>{if(!au.loop&&currentAudio!=null&&currentAudio<state.audio.length-1)playAudio(currentAudio+1)};au.onloadedmetadata=updatePlayer;
    if(currentAudio!=null&&state.audio[currentAudio]){au.src=state.audio[currentAudio].url;au.volume=.8;}
  }
  function addAudio(file){const type=confirm('¿Este archivo es un audiolibro?\nAceptar = Audiolibro · Cancelar = Audio de estudio')?'book':'study';state.audio.push({id:id(),name:file.name.replace(/\.[^.]+$/,''),type,url:URL.createObjectURL(file)});save();currentAudio=state.audio.length-1;renderAudio()}
  function playAudio(i){if(!state.audio[i])return;currentAudio=i;renderAudio();const a=document.getElementById('lumiAudio');a.play().catch(()=>{});document.querySelectorAll('.audio-card').forEach((x,j)=>x.classList.toggle('playing',j===i));document.getElementById('retroMain').textContent='Ⅱ'}
  function toggleAudio(){const a=document.getElementById('lumiAudio');if(!a.src&&state.audio.length){playAudio(0);return}a.paused?a.play():a.pause();document.getElementById('retroMain').textContent=a.paused?'▶':'Ⅱ'}
  function updatePlayer(){const a=document.getElementById('lumiAudio');if(!a.duration)return;document.getElementById('retroProgress').style.width=(a.currentTime/a.duration*100)+'%';document.getElementById('retroTime').textContent=fmt(a.currentTime)+' / '+fmt(a.duration)}
  const fmt=n=>{n=Math.floor(n||0);return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')};
  function removeAudio(x){state.audio=state.audio.filter(a=>a.id!==x);if(currentAudio>=state.audio.length)currentAudio=null;save();renderAudio()}
  async function addPdf(file){
    if(!window.pdfjsLib){alert('El lector PDF todavía se está cargando.');return}
    const subject=prompt('Materia para este PDF (ej. Historia, Matemática, Lengua):','General')||'General';
    const url=URL.createObjectURL(file);let text='';try{const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;for(let i=1;i<=pdf.numPages;i++){const c=await (await pdf.getPage(i)).getTextContent();text+=c.items.map(x=>x.str).join(' ')+'\n'}}catch(e){}
    state.pdfs.push({id:id(),name:file.name.replace(/\.[^.]+$/,''),subject,text,url,pages:0,created:new Date().toISOString()});save();renderPdf();
  }
  function renderPdf(){const box=document.getElementById('libraryPdf');if(!box)return;const subjects=[...new Set(state.pdfs.map(p=>p.subject))];box.innerHTML=`<div class="library-toolbar"><div><b>Biblioteca de PDFs</b><small>Organizá tus apuntes por materia y leelos en voz alta.</small></div><label class="primary small library-upload">+ Subir PDF<input id="pdfLibraryInput" type="file" accept="application/pdf,.pdf" multiple hidden></label></div>${subjects.length?subjects.map(s=>`<div class="pdf-subject"><div class="pdf-subject-head"><span class="subject-dot"></span><h3>${esc(s)}</h3><small>${state.pdfs.filter(p=>p.subject===s).length} archivo(s)</small></div><div class="pdf-grid">${state.pdfs.filter(p=>p.subject===s).map(p=>`<article class="pdf-card"><div class="pdf-sheet">PDF</div><div><strong>${esc(p.name)}</strong><small>${p.text.length?Math.round(p.text.length/1000)+'k caracteres':'PDF escaneado o sin texto'}</small></div><div class="pdf-actions"><button class="soft small" data-read="${p.id}">Leer</button><button class="soft small" data-speak="${p.id}">Voz</button><button class="soft small" data-pdfdel="${p.id}">×</button></div></article>`).join('')}</div></div>`).join(''):'<div class="library-empty">Todavía no hay PDFs. Subí uno y elegí su materia.</div>'}`;box.querySelector('#pdfLibraryInput').onchange=e=>[...e.target.files].forEach(addPdf);box.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>openReader(b.dataset.read));box.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speakPdf(b.dataset.speak));box.querySelectorAll('[data-pdfdel]').forEach(b=>b.onclick=()=>removePdf(b.dataset.pdfdel))}
  function removePdf(x){state.pdfs=state.pdfs.filter(p=>p.id!==x);save();renderPdf()}
  function openReader(x){const p=state.pdfs.find(p=>p.id===x);if(!p)return;let old=document.getElementById('lumiReader');if(old)old.remove();const m=document.createElement('div');m.id='lumiReader';m.className='modal-backdrop';m.innerHTML=`<div class="lumi-modal library-reader"><button class="icon-btn reader-close">×</button><span class="section-kicker">${esc(p.subject)}</span><h2>${esc(p.name)}</h2><div class="reader-tools"><button class="primary small reader-speak">Leer en voz alta</button><button class="soft small reader-stop">Detener</button></div><article class="reader-text">${esc(p.text||'Este PDF no contiene texto seleccionable. No se puede leer en voz alta desde el navegador.')}</article></div>`;document.body.appendChild(m);m.querySelector('.reader-close').onclick=()=>{speechSynthesis.cancel();m.remove()};m.querySelector('.reader-speak').onclick=()=>speakText(p.text);m.querySelector('.reader-stop').onclick=()=>speechSynthesis.cancel()}
  function speakPdf(x){const p=state.pdfs.find(p=>p.id===x);if(p)speakText(p.text)}
  function speakText(text){if(!('speechSynthesis' in window)){alert('La lectura en voz alta no está disponible en este navegador.');return}speechSynthesis.cancel();const clean=String(text||'').trim();if(!clean)return;const chunks=clean.match(/.{1,1800}(?:\s|$)/g)||[clean];let i=0;const next=()=>{if(i>=chunks.length)return;const u=new SpeechSynthesisUtterance(chunks[i++]);u.lang=document.documentElement.lang||'es-AR';u.rate=.92;u.pitch=1;u.onend=next;speechSynthesis.speak(u)};next()}
  document.addEventListener('DOMContentLoaded',()=>{setTimeout(inject,250);setTimeout(inject,1200)});
  window.addEventListener('hashchange',()=>setTimeout(inject,100));
})();
