/* LUMI LIBRARY — rebuilt UI, same functionality */
(function(){
const KEY='lumi-library-v5';
const old=JSON.parse(localStorage.getItem('lumi-library-v4')||'{"audio":[],"pdfs":[],"playlists":[]}');
const state=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(old));
state.audio ||= []; state.pdfs ||= []; state.playlists ||= [];
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
let current=null,audio=null,playlist=null;
function mount(){
 const root=document.getElementById('lumiLibrary'); if(!root||root.dataset.libraryV2)return; root.dataset.libraryV2='1';
 root.innerHTML=`<div class="lumi-v2"><div class="lv-head"><div><div class="lv-eyebrow">LUMI LIBRARY</div><h3>Biblioteca</h3><p>Escuchá, leé y organizá todo tu material.</p></div><div class="lv-stats"><span><b id="lvPdfCount">0</b>PDF</span><span><b id="lvAudioCount">0</b>audios</span><span><b id="lvPlaylistCount">0</b>playlists</span></div></div><div class="lv-tabs"><button class="lv-tab active" data-tab="audio">Audio</button><button class="lv-tab" data-tab="pdf">PDF</button></div><section id="lvAudio" class="lv-panel"></section><section id="lvPdf" class="lv-panel hidden"></section></div>`;
 root.querySelectorAll('.lv-tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab)); renderAudio(); renderPdf();
}
function tab(t){document.querySelectorAll('#lumiLibrary .lv-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));document.getElementById('lvAudio').classList.toggle('hidden',t!=='audio');document.getElementById('lvPdf').classList.toggle('hidden',t!=='pdf')}
function renderAudio(){
 const box=document.getElementById('lvAudio'); if(!box)return; const p=playlist?state.playlists.find(x=>x.id===playlist):null; const list=p?state.audio.filter(x=>p.tracks.includes(x.id)):state.audio;
 document.getElementById('lvAudioCount').textContent=state.audio.length;document.getElementById('lvPlaylistCount').textContent=state.playlists.length;
 box.innerHTML=`<div class="lv-audio-layout"><aside class="lv-side"><div class="lv-side-title"><strong>PLAYLISTS</strong><button class="lv-plus" id="lvNew">+</button></div><button class="lv-playlist ${!p?'active':''}" data-pl="all"><span>Todos los audios</span><small>${state.audio.length}</small></button>${state.playlists.map(x=>`<button class="lv-playlist ${p?.id===x.id?'active':''}" data-pl="${x.id}"><span>${esc(x.name)}</span><small>${x.tracks.length}</small></button>`).join('')}<label class="lv-upload">+ Añadir audio<input id="lvAudioInput" type="file" accept="audio/*" multiple></label></aside><main class="lv-main"><div class="lv-main-head"><div><div class="lv-eyebrow">${p?'PLAYLIST':'AUDIO'}</div><h4>${p?esc(p.name):'Audios de estudio'}</h4><p>${list.length} pista${list.length===1?'':'s'}</p></div>${p?'<button class="lv-btn" id="lvDelete">Eliminar</button>':''}</div><div class="lv-audios">${list.map(a=>{const i=state.audio.indexOf(a);return `<article class="lv-audio ${current===i?'current':''}"><div class="lv-icon">${a.type==='book'?'▤':'♪'}</div><div><strong>${esc(a.name)}</strong><small>${a.type==='book'?'Audiolibro':'Audio de estudio'}</small></div><div class="lv-audio-actions"><button class="lv-btn" data-play="${i}">${current===i&&audio&&!audio.paused?'PAUSA':'PLAY'}</button><button class="lv-btn" data-add="${a.id}">${p?'−':'+'}</button></div></article>`}).join('')||'<div class="lv-empty">Todavía no hay audios. Añadí el primero desde la izquierda.</div>'}</div><div class="lv-deck"><div class="lv-deck-top"><span>LUMI AUDIO</span><span id="lvStatus">${current!=null?'READY':'EMPTY'}</span></div><div class="lv-now"><div class="lv-disc"></div><div style="min-width:0"><span>NOW PLAYING</span><strong id="lvTitle">${current!=null?esc(state.audio[current]?.name):'Elegí una pista'}</strong><small id="lvType">${current!=null?(state.audio[current]?.type==='book'?'AUDIOBOOK':'STUDY AUDIO'):'Tu reproductor'}</small></div></div><div class="lv-progress"><i id="lvProgress"></i></div><div class="lv-time"><span id="lvCurrent">00:00</span><span id="lvDuration">00:00</span></div><div class="lv-controls"><button id="lvPrev">PREV</button><button id="lvMain" class="main">${current!=null?'PLAY':'START'}</button><button id="lvNext">NEXT</button><button id="lvLoop">LOOP</button></div><div class="lv-volume">VOL <input id="lvVolume" type="range" min="0" max="1" step=".01" value=".8"></div><audio id="lvAudioEl" preload="metadata"></audio></div></main></div>`;
 box.querySelector('#lvNew').onclick=newPlaylist; box.querySelector('#lvAudioInput').onchange=e=>[...e.target.files].forEach(addAudio);
 box.querySelectorAll('[data-pl]').forEach(b=>b.onclick=()=>{playlist=b.dataset.pl==='all'?null:b.dataset.pl;renderAudio()}); box.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(+b.dataset.play));
 box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const id=b.dataset.add;if(p){p.tracks=p.tracks.filter(x=>x!==id);save();renderAudio()}else addTrack(id)});
 if(p)box.querySelector('#lvDelete').onclick=()=>{state.playlists=state.playlists.filter(x=>x.id!==p.id);playlist=null;save();renderAudio()};
 audio=document.getElementById('lvAudioEl'); audio.volume=.8; audio.ontimeupdate=update;audio.onloadedmetadata=update;audio.onplay=()=>setStatus('PLAYING');audio.onpause=()=>setStatus('PAUSED');audio.onended=()=>{if(!audio.loop&&state.audio.length)play((current+1)%state.audio.length)};
 box.querySelector('#lvMain').onclick=toggle;box.querySelector('#lvPrev').onclick=()=>state.audio.length&&play((current==null?0:(current-1+state.audio.length)%state.audio.length));box.querySelector('#lvNext').onclick=()=>state.audio.length&&play((current==null?0:(current+1)%state.audio.length));box.querySelector('#lvVolume').oninput=e=>audio.volume=+e.target.value;box.querySelector('#lvLoop').onclick=e=>{audio.loop=!audio.loop;e.currentTarget.classList.toggle('on',audio.loop)};
 if(current!=null&&state.audio[current]){audio.src=state.audio[current].url;audio.load()}
}
function newPlaylist(){const n=prompt('Nombre de la playlist:','Estudio');if(!n?.trim())return;const p={id:uid(),name:n.trim(),tracks:[]};state.playlists.push(p);playlist=p.id;save();renderAudio()}
function addTrack(id){if(!state.playlists.length){newPlaylist();const p=state.playlists.find(x=>x.id===playlist);if(p&&!p.tracks.includes(id))p.tracks.push(id)}else{const p=state.playlists.find(x=>x.id===playlist)||state.playlists[0];if(!p.tracks.includes(id))p.tracks.push(id);playlist=p.id}save();renderAudio()}
function addAudio(file){const type=(prompt('B = audiolibro / E = audio de estudio','E')||'E').toLowerCase()==='b'?'book':'study';state.audio.push({id:uid(),name:file.name.replace(/\.[^.]+$/,''),type,url:URL.createObjectURL(file)});current=state.audio.length-1;save();renderAudio()}
function play(i){if(!state.audio[i])return;current=i;renderAudio();audio.play().catch(()=>{})}
function toggle(){if(!audio)return;if(!audio.src&&state.audio.length){play(0);return}audio.paused?audio.play():audio.pause()}
function setStatus(s){const x=document.getElementById('lvStatus'),b=document.getElementById('lvMain');if(x)x.textContent=s;if(b)b.textContent=s==='PLAYING'?'PAUSA':'PLAY'}
function update(){if(!audio||!audio.duration)return;const p=document.getElementById('lvProgress');if(p)p.style.width=(audio.currentTime/audio.duration*100)+'%';const c=document.getElementById('lvCurrent'),d=document.getElementById('lvDuration');if(c)c.textContent=fmt(audio.currentTime);if(d)d.textContent=fmt(audio.duration)}
function fmt(n){n=Math.floor(n||0);return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
async function addPdf(file){if(!window.pdfjsLib)return;const subject=prompt('Materia para este PDF:','General')||'General';let text='';try{const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;for(let i=1;i<=pdf.numPages;i++){const c=await pdf.getPage(i).then(p=>p.getTextContent());text+=c.items.map(x=>x.str).join(' ')+'\n'}}catch(e){}state.pdfs.push({id:uid(),name:file.name.replace(/\.[^.]+$/,''),subject,text,url:URL.createObjectURL(file),created:new Date().toISOString()});save();renderPdf()}
function renderPdf(){const box=document.getElementById('lvPdf');if(!box)return;document.getElementById('lvPdfCount').textContent=state.pdfs.length;const subjects=[...new Set(state.pdfs.map(x=>x.subject))];box.innerHTML=`<div class="lv-pdf-tools"><div><strong>Documentos</strong><small>PDFs organizados por materia.</small></div><label class="lv-upload" style="margin:0">+ Añadir PDF<input id="lvPdfInput" type="file" accept="application/pdf,.pdf" multiple></label></div>${subjects.map(s=>`<div style="margin-top:18px"><div class="lv-eyebrow">${esc(s)}</div><div class="lv-pdfs">${state.pdfs.filter(x=>x.subject===s).map(p=>`<article class="lv-pdf"><div class="lv-pdf-icon">PDF</div><div><strong>${esc(p.name)}</strong><small>${p.text.length?Math.round(p.text.length/1000)+'k caracteres':'Sin texto'}</small></div><div class="lv-pdf-actions"><button class="lv-btn" data-read="${p.id}">Abrir</button><button class="lv-btn" data-speak="${p.id}">Voz</button></div></article>`).join('')}</div></div>`).join('')||'<div class="lv-empty">Todavía no hay PDFs.</div>'}`;box.querySelector('#lvPdfInput').onchange=e=>[...e.target.files].forEach(addPdf);box.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>reader(b.dataset.read));box.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speakPdf(b.dataset.speak))}
function reader(id){const p=state.pdfs.find(x=>x.id===id);if(!p)return;document.getElementById('lumiReader')?.remove();const m=document.createElement('div');m.id='lumiReader';m.className='modal-backdrop';m.innerHTML=`<div class="lumi-modal library-reader"><button class="icon-btn reader-close">×</button><div class="lv-eyebrow">${esc(p.subject)}</div><h2>${esc(p.name)}</h2><div class="reader-tools"><button class="primary small reader-speak">Leer en voz alta</button><button class="soft small reader-stop">Detener</button></div><article class="reader-text">${esc(p.text||'Este PDF no contiene texto seleccionable.')}</article></div>`;document.body.appendChild(m);m.querySelector('.reader-close').onclick=()=>{speechSynthesis.cancel();m.remove()};m.querySelector('.reader-speak').onclick=()=>speakText(p.text);m.querySelector('.reader-stop').onclick=()=>speechSynthesis.cancel()}
function speakPdf(id){const p=state.pdfs.find(x=>x.id===id);if(p)speakText(p.text)}
function speakText(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const chunks=String(text||'').trim().match(/.{1,1800}(?:\s|$)/g)||[''];let i=0;const next=()=>{if(i>=chunks.length)return;const u=new SpeechSynthesisUtterance(chunks[i++]);u.lang='es-AR';u.rate=.92;u.onend=next;speechSynthesis.speak(u)};next()}
document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,100));
})();
