/* LUMI Games — four playable study modes */
(function(){
  const q=id=>document.getElementById(id), area=()=>q('gameArea');
  const cards=()=>JSON.parse(localStorage.getItem('lumi-flashcards')||'[]');
  const notes=()=>JSON.parse(localStorage.getItem('lumi-notes')||'[]');
  const fallback=[['¿Qué tema querés repasar?','Elegí una respuesta para practicar.'],['¿Cuál es una buena forma de estudiar?','Repasar activamente y volver sobre los errores.'],['¿Qué conviene hacer después de un error?','Entender por qué ocurrió y volver a intentarlo.']];
  function shell(title,sub,body){area().innerHTML=`<div class="game-screen"><div class="game-screen-head"><div><span class="section-kicker">LUMI PLAY</span><h3>${title}</h3><p>${sub}</p></div><button class="soft small" id="gameBack">Volver</button></div>${body}</div>`;q('gameBack').onclick=menu}
  function menu(){area().innerHTML=`<div class="game-welcome"><div class="game-icon"></div><span class="section-kicker">LUMI PLAY</span><h3>Elegí una experiencia</h3><p>Cuatro formas distintas de estudiar con el mismo contenido.</p><div class="game-menu-grid"><button class="game-choice" id="gQuiz"><b>Quiz rápido</b><small>Preguntas con opciones y puntaje.</small></button><button class="game-choice" id="gMemory"><b>Memoria</b><small>Encontrá pares y recordá conceptos.</small></button><button class="game-choice" id="gNotes"><b>Quiz de apuntes</b><small>Convertí tus notas guardadas en preguntas.</small></button><button class="game-choice" id="gFocus"><b>Misión Focus</b><small>Una sesión ajustable con progreso visual.</small></button></div></div>`;q('gQuiz').onclick=quiz;q('gMemory').onclick=memory;q('gNotes').onclick=noteQuiz;q('gFocus').onclick=focus}
  function quiz(source){const data=source||fallback.map(x=>({q:x[0],a:x[1]}));let i=0,score=0;function draw(){const x=data[i];const opts=[x.a,'No es la respuesta principal','Es una idea relacionada','Ninguna de las anteriores'].sort(()=>Math.random()-.5);shell('Quiz rápido','Elegí la opción que mejor responde.',`<div class="game-progress"><span>${i+1}/${data.length}</span><span>${score} puntos</span></div><div class="game-question"><h4>${x.q}</h4><div class="game-options">${opts.map((o,n)=>`<button data-o="${n}">${o}</button>`).join('')}</div></div>`);area().querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{const ok=b.textContent===x.a;if(ok)score++;b.classList.add(ok?'correct':'wrong');setTimeout(()=>{i++;i<data.length?draw():result()},450)})}function result(){shell('Resultado','Terminaste esta ronda.',`<div class="game-result"><strong>${score}/${data.length}</strong><p>Volvé a jugar para consolidar lo que costó más.</p><button class="primary small" id="again">Jugar de nuevo</button></div>`);q('again').onclick=()=>quiz(data)}draw()}
  function memory(){let pairs=(cards().length?cards().slice(0,6).map((x,i)=>({a:x.front||x.question||'Concepto '+(i+1),b:x.back||x.answer||'Respuesta'})):fallback.map(x=>({a:x[0],b:x[1]})));let deck=[];pairs.forEach((p,i)=>{deck.push({id:i,text:p.a,type:'a'});deck.push({id:i,text:p.b,type:'b'})});deck.sort(()=>Math.random()-.5);let open=[],matched=0;function draw(){shell('Memoria','Encontrá cada concepto junto con su respuesta.',`<div class="memory-grid">${deck.map((c,i)=>`<button class="memory-tile ${open.includes(i)||c.matched?'revealed':''}" data-i="${i}"><span>${open.includes(i)||c.matched?c.text:'LUMI'}</span></button>`).join('')}</div><div class="game-progress"><span>${matched}/${pairs.length} pares</span></div>`);area().querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(open.includes(i)||deck[i].matched||open.length===2)return;open.push(i);draw();if(open.length===2){setTimeout(()=>{const [a,b]=open;if(deck[a].id===deck[b].id&&deck[a].type!==deck[b].type){deck[a].matched=deck[b].matched=true;matched++;}open=[];matched===pairs.length?result():draw()},650)}})}function result(){shell('Memoria completa','Buen trabajo.',`<div class="game-result"><strong>Todos los pares</strong><p>Volvé a los conceptos que más te costaron.</p><button class="primary small" id="again">Repetir</button></div>`);q('again').onclick=memory}draw()}
  function noteQuiz(){const ns=notes();if(!ns.length){shell('Quiz de apuntes','Primero guardá algunas notas.',`<div class="game-result"><strong>No hay apuntes todavía</strong><p>Creá una nota y después volvé acá.</p></div>`);return}const data=ns.slice(0,8).map(n=>({q:n.title||'Nota',a:(n.content||'').slice(0,180)}));quiz(data)}
  function focus(){shell('Misión Focus','Elegí cuánto querés concentrarte.',`<div class="focus-game"><strong id="gameTimer">25:00</strong><input id="gameRange" type="range" min="5" max="120" value="25" step="5"><output id="gameValue">25 min</output><button class="primary small" id="gameStart">Empezar</button><div class="focus-ring" id="focusRing"></div></div>`);let total=25*60,left=total,timer=null;q('gameRange').oninput=e=>{total=left=+e.target.value*60;q('gameValue').textContent=e.target.value+' min';q('gameTimer').textContent=fmt(left)};q('gameStart').onclick=()=>{if(timer)return;timer=setInterval(()=>{left--;q('gameTimer').textContent=fmt(left);q('focusRing').style.setProperty('--progress',((total-left)/total*360)+'deg');if(left<=0){clearInterval(timer);timer=null;q('gameStart').textContent='Completado'}},1000)};function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}}
  function wire(){if(q('startQuiz'))q('startQuiz').onclick=quiz;if(q('startMemory'))q('startMemory').onclick=memory;if(q('flashGame'))q('flashGame').onclick=memory;if(q('noteQuiz'))q('noteQuiz').onclick=noteQuiz;if(q('focusGame'))q('focusGame').onclick=focus;menu()}
  document.addEventListener('DOMContentLoaded',()=>setTimeout(wire,700));
})();